#!/bin/bash
touch .doing
mp=$1
tp=$2
img_srv=$3 # image server
srv2='bu.mkklcdnbuv1.com'
if [[ "$tp" = "" ]]; then
    tp=$(basename "$mp")
fi

curl "$mp" 2>/dev/null | grep -oE '<a\s+href="[^"]+"' | grep -oE "https?://[^\"]+$tp[^\"]*chapter[_-][^\"]+" | sort -V | uniq |
while read -r purl; do
    chap=$(basename "$purl")
    if [[ ! -d "$chap" ]] || [[ -f "$chap/.doing" ]]; then
        echo  "$chap" > .doing
        mkdir -p "$chap"
        cd "$chap"
            touch .doing
            if [[ "$img_srv" == 2 ]]; then
                curl "$purl" |grep -oE '<img(\s+class="img_content"|)\s+src="[^"]*"' |grep -oE 'https?://[^"]+/[0-9]+\.[^/"]+' |sed -nr "s#(https?://)([^/]+)(/.*)#\1$srv2\3#p" |mwget -c -i -
            else
                curl "$purl" |grep -oE '<img(\s+class="img_content"|)\s+src="[^"]*"' |grep -oE 'https?://[^"]+/[0-9]+\.[^/"]+' |mwget -c -i -
            fi
            img2html
            rm .doing
        cd - >/dev/null
    else
        echo "Directory exists: $chap [Skipped]"
    fi
done
find . -type d -empty -delete
mv -f .doing .done
