#!/bin/bash
touch .doing
mp=$1
tp=$2
img_srv=${3:-1} # image server
srv2='bu.mkklcdnbuv1.com'


curl "$mp" 2>/dev/null | grep -oP 'href="[^"]+"' | grep -oP "https?://[^\"]+${tp}[^\"]*chapter[_-][^\"]+" | sort -V | uniq |
while read -r purl; do
    chap=$(basename "$purl")
    if [[ ! -d "$chap" ]] || [[ -f "$chap/.doing" ]]; then
        echo  "$chap" > .doing
        mkdir -p "$chap"
        cd "$chap"
            touch .doing
            echo "URL: $purl"
            if [[ "$img_srv" == 2 ]]; then
                curl "$purl" |grep -oE '<img(\s+class="img_content"|)\s+src="[^"]*"' |grep -oE 'https?://[^"]+/[0-9]+\.[^/"]+' |sed -nr "s#(https?://)([^/]+)(/.*)#\1$srv2\3#p" |mwget -c -i -
            elif [[ "$img_srv" == 0 ]]; then
                curl "$purl" |grep -oE '<img[^>]+src="[^"]+"' |grep -oE 'https?://[^"]+' |wget -c -i -
            else
                # curl "$purl" |grep -oE 'https?://[^"]*/wp-content/uploads/WP-manga/data/[^"]*\.(jpg|png|gif)[^"]*' |wget -c -i -
                curl "$purl" |grep -oE '<img[^>]+src="[^"]+"' |grep -oE "https?://[^\"]+$chap[^\"]+" |mwget -c -i -

            fi
            rnm -rs '/\.(jpe?g|png).*/.\1/' -dp -1 -fo -y *
            rnm -rs '/[?].*$//' -fo -dp -1 -y *
            img2html
            rm .doing
        cd - >/dev/null
    else
        echo "Directory exists: $chap [Skipped]"
    fi
done
find . -type d -empty -delete
mv -f .doing .done
