#!/bin/sh
p_name=gitrpush
p_version=0.0.1
ver_info="
Name        : $p_name
Version     : $p_version
"
help="
########## $p_name #############
git remote push
pushes to remote host through ssh

Depends on: jssh (https://github.com/neurobin/jssh)

Options:
    -p : pull first
    -f : force push
    -m : comment
    -wd: work dir
    -d : domain
    -v : show version info
    -h : show help
"

pull=false
comment="update"

s="$(git remote show origin |grep -i 'push[[:blank:]]\+url')"
dom="$(echo "$s" |sed -n 's/.*@\([^:]\+\):.*/\1/p')"
wd="$(echo "$s" |sed -n "s/.*$dom:[0-9]\+\([^[:blank:]]*\)[[:blank:]]*$/\1/p")"

force=false
for op in "$@";do
    case "$op" in
        -v|--version)
            echo "$ver_info"
            shift
            exit 0
            ;;
        -h|--help)
            echo "$help"
            shift
            exit 0
            ;;
        -p|--pull)
            pull=true
            shift
            ;;
        -f|--force)
            force=true
            shift
            ;;
        -m|--comment)
            shift
            comment="$1"
            shift
            ;;
        -wd|--work-dir)
            shift
            wd="$1"
            shift
            ;;
         -d|--domain)
            shift
            dom="$1"
            shift
            ;;
        
        -*)
            echo "E: Invalid option: $1"
            shift
            exit 1
            ;;
    esac
done



if [ -z "$dom" ]; then
    echo "Domain (used with jssh) name must be given"
    exit 1
fi

echo "
*** Domain: $dom
*** Direct: $wd
"

if $pull; then
    if git pull origin master; then
        echo 'Pulled from remote successfully'
    else
        echo 'Failed to pull from remote'
    fi
fi

echo '*** Local commit'
{ git add --all :/ || git add --all; } &&
git commit -m "$comment"

#login to remote and detach the branch

echo '*** detach remote'
if jssh "$dom" "cd $wd
    { git add --all :/ || git add --all; } &&
    git commit -m "$comment"
    git checkout --detach || git checkout old-master || git checkout -b old-master
    git merge master
    "; then
    echo 'Detached remote branch successfully'
else
    echo 'E: Failed to detach remote branch'; exit 1;
fi

# push to remote
echo '*** Push to remote'
p_flags=''
if $force; then
    p_flags="$p_flags -f"
fi
if git push $p_flags --all; then
    echo "Push to remote successful
Re-attaching remote branch..."
else
    echo 'E: Failed to push to remote'; exit 1;
fi

# reattach remote branch
echo '*** Re-attach remote'
if jssh "$dom" "cd '$wd'
    { git add --all :/ || git add --all; } &&
    git commit -m '$comment'
    git checkout master &&
    echo 'Re-attached remote branch successfully'
    ## manage permission
    find . -type f -name '*.php' -exec sh -c 'touch -r \"\$0\" .timestamp.nb; chmod 600 \"\$0\"; touch -r .timestamp.nb \"\$0\"; rm .timestamp.nb' {} \; &&
    echo 'Fixed php file permission'
    find . -type d -exec sh -c 'touch -r \"\$0\" .timestamp.nb; chmod 755 \"\$0\"; touch -r .timestamp.nb \"\$0\"; rm .timestamp.nb' {} \; &&
    echo 'Fixed directory permission'
    "; then
    echo 'Successfully re-attached remote branch'
else
    echo "E: Failed to re-attach remote branch"; exit 1;
fi


