#!/bin/sh

tag=$1
msg=$2

if [ "$tag" = '' ]; then
    echo "E: tag must be given"
    exit 1
fi

if [ "$msg" = '' ]; then
    echo "E: message can not be empty"
    exit 1
fi

cbranch=$(git branch |sed -n 's/^*[[:blank:]]*\(.*\)$/\1/p')

echo "Current branch: $cbranch"
printf "Continue with current branch?: (Y/n): "
read c
if [ "$c" != Y ] && [ "$c" != y ]]; then
    echo "E: interrupted"
    exit 1
fi

git tag -f -u 6BDAA871 -s "$tag" -m "$msg"
git push -f --tags
