#!/bin/bash
logdir="$HOME/.neurobin/jssh"
mkdir -p  "$logdir"
[[ $1 == "" ]] && echo "Domain name required. Abort!" && exit 1;
dom="$1"
configfile="$logdir/${dom}.conf"
[[ ! -f "$configfile" ]] && echo "Configuration file doesn't exist. Abort!" && exit 1;
host="$(grep -sioP '(?<=^Host=).*' "$configfile")"
port="$(grep -sioP '(?<=^Port=).*' "$configfile")"
user="$(grep -sioP '(?<=^User=).*' "$configfile")"
[[ $host == "" ]] && host="$dom"
[[ $port == "" ]] && { echo "Port required";exit 1; }
[[ $user == "" ]] && { echo "username required";exit 1; }
shift
ssh -p "$port" "$user@$host" "$*"
