#!/bin/sh
cookies_file="/tmp/__mwget_cookies.txt"
wget  --load-cookies "$cookies_file" --keep-session-cookies --save-cookies "$cookies_file" --header="Accept: text/html" --user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:21.0) Gecko/20100101 Firefox/21.0" ${1+"$@"}
