#!/bin/sh

wget --header="User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" --header="Accept: imtext/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" --header="Accept-Language: en-US,en-GB;q=0.9,en;q=0.8" --header="Accept-Encoding: gzip, deflate, br" --header="Referer: https://www.reddit.com" ${1+"$@"}
