#!/bin/bash
repo="$1"
logdir="$HOME/.neurobin/webgit"
configfile="$logdir/.config"
mkdir -p "$logdir" && touch $configfile || exit 1
host="$(grep -sioP '(?<=^Host=).*' "$configfile")"
port="$(grep -sioP '(?<=^Port=).*' "$configfile")"
user="$(grep -sioP '(?<=^User=).*' "$configfile")"
gitmirrordir="$(grep -sioP '(?<=^GitMirror=).*' "$configfile")"
gitbasedir="$(grep -sioP '(?<=^BaseDir=).*' "$configfile")"
[[ $host != "" ]] &&
[[ $port != "" ]] &&
[[ $user != "" ]] &&
[[ $gitmirrordir != "" ]] &&
[[ $gitbasedir != "" ]] || { echo "missing credentials";exit 1; }
reponame="${repo##*/}.git"
[[ $repo == "" ]] && { echo "reponame required"; exit 1; }
#ssh -p "$port" "$user@$host" <<EOF
#mkdir -p $gitmirrordir/$reponame && cd $gitmirrordir/$reponame && git init --bare &&
#mkdir -p $gitbasedir/$repo &&
#echo "#!/bin/sh
#GIT_WORK_TREE=$gitbasedir/$repo git checkout -f" > hooks/post-receive
#EOF
ssh -p "$port" "$user@$host" <<EOF
mkdir -p $gitbasedir/$repo && cd $gitbasedir/$repo && 
[[ ! -d .git ]] && git init
EOF
echo "remote=ssh://$user@$host:$port$gitbasedir/$repo" > "$logdir/$reponame"
