#!/bin/bash
opts=( "$@" )
#if no argument is passed this for loop will be skipped
for ((i=0;i<$#;i++)) do
case "${opts[$i]}" in
   -h)
   #dummy help option
   echo "Options are [-abc value], -h"
   
	;;
	
   
   *)
   #other unknown options
   echo invalid option
 	break
	
	;;
esac
done
